name: Build & Deploy
 
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: sample.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true

      - uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: sample.pdf